[package]
name = "gluesql-redb-storage"
authors = ["Park Ma <park-ma@hotmail.com>"]
version.workspace = true
edition.workspace = true
description.workspace = true
license.workspace = true
repository.workspace = true
documentation.workspace = true

[dependencies]
gluesql-core.workspace = true
async-trait = "0.1"
serde = { version = "1", features = ["derive"] }
redb = "1.0"

[dev-dependencies]
test-suite.workspace = true
tokio = { version = "1", features = ["rt", "macros"] }
futures = "0.3"
