[package]
name = "gluesql-redb-storage"
authors = ["Taehoon Moon <taehoon.moon@outlook.com>"]
version.workspace = true
edition.workspace = true
description.workspace = true
license.workspace = true
repository.workspace = true
documentation.workspace = true

[dependencies]
gluesql-core.workspace = true
redb = "2.6"
async-trait = "0.1"
serde = { version = "1", features = ["derive"] }
futures = "0.3"
thiserror = "2.0.3"
bincode = "1.3.3"
uuid = { version = "1.11.0", features = ["v7"] }
async-stream = "0.3.6"

[dev-dependencies]
test-suite.workspace = true
tokio = { version = "1", features = ["rt", "macros"] }
