[package]
name = "sled-storage-glue"
version = "0.1.0"
authors = ["Taehoon Moon <taehoon.moon@outlook.com>"]
edition = "2018"
description = ""
license = "Apache-2.0"
# repository = "https://github.com/gluesql/gluesql"
# documentation = "https://docs.rs/gluesql/"

[dependencies]
bincode = { version = "1.3", optional = true }
sled = { version = "0.34.6", optional = true }

[dependencies.gluesql_core]
version = "0.8"
package = "gluesql"
default-features = false
features = ["sorter", "alter-table", "index", "transaction"]

