[package]
name = "gluesql-sqlite-storage"
authors = ["GlueSQL Contributors"]
version.workspace = true
edition.workspace = true
description.workspace = true
license.workspace = true
repository.workspace = true
documentation.workspace = true

[dependencies]
gluesql-core.workspace = true
async-trait = "0.1"
tokio = { version = "1", features = ["macros", "rt"] }
tokio-rusqlite = "0.5"
rusqlite = { version = "0.31", features = ["bundled"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
chrono = { version = "0.4", features = ["serde"] }
base64 = "0.22"
uuid = { version = "1", features = ["serde", "v4"] }
rust_decimal = { version = "1", features = ["serde"] }
futures = "0.3"

[dev-dependencies]
test-suite.workspace = true
tokio = { version = "1", features = ["rt-multi-thread", "macros"] }

[lints]
workspace = true
