// This file is automatically generated, so please do not edit it.
// Generated by `flutter_rust_bridge`@ 2.0.0-dev.39.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import '../lib.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
import 'value.dart';
part 'payload.freezed.dart';

@freezed
sealed class Payload with _$Payload {
  const Payload._();

  const factory Payload.showColumns(
    List<(String, DataType)> field0,
  ) = Payload_ShowColumns;
  const factory Payload.create() = Payload_Create;
  const factory Payload.insert(
    BigInt field0,
  ) = Payload_Insert;
  const factory Payload.select({
    required List<String> labels,
    required List<List<Value>> rows,
  }) = Payload_Select;
  const factory Payload.selectMap(
    List<Map<String, Value>> field0,
  ) = Payload_SelectMap;
  const factory Payload.delete(
    BigInt field0,
  ) = Payload_Delete;
  const factory Payload.update(
    BigInt field0,
  ) = Payload_Update;
  const factory Payload.dropTable() = Payload_DropTable;
  const factory Payload.dropFunction() = Payload_DropFunction;
  const factory Payload.alterTable() = Payload_AlterTable;
  const factory Payload.createIndex() = Payload_CreateIndex;
  const factory Payload.dropIndex() = Payload_DropIndex;
  const factory Payload.startTransaction() = Payload_StartTransaction;
  const factory Payload.commit() = Payload_Commit;
  const factory Payload.rollback() = Payload_Rollback;
  const factory Payload.showVariable(
    PayloadVariable field0,
  ) = Payload_ShowVariable;
}
