// This file is automatically generated, so please do not edit it.
// Generated by `flutter_rust_bridge`@ 2.0.0-dev.32.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
import 'simple.dart';
part 'value.freezed.dart';

@freezed
sealed class DartValue with _$DartValue {
  const DartValue._();

  const factory DartValue.bool(
    bool field0,
  ) = DartValue_Bool;
  const factory DartValue.i8(
    int field0,
  ) = DartValue_I8;
  const factory DartValue.i16(
    int field0,
  ) = DartValue_I16;
  const factory DartValue.i32(
    int field0,
  ) = DartValue_I32;
  const factory DartValue.i64(
    int field0,
  ) = DartValue_I64;
  const factory DartValue.i128(
    I128 field0,
  ) = DartValue_I128;
  const factory DartValue.u8(
    int field0,
  ) = DartValue_U8;
  const factory DartValue.u16(
    int field0,
  ) = DartValue_U16;
  const factory DartValue.u32(
    int field0,
  ) = DartValue_U32;
  const factory DartValue.u64(
    int field0,
  ) = DartValue_U64;
  const factory DartValue.u128(
    U128 field0,
  ) = DartValue_U128;
  const factory DartValue.f32(
    double field0,
  ) = DartValue_F32;
  const factory DartValue.f64(
    double field0,
  ) = DartValue_F64;
  const factory DartValue.decimal(
    Decimal field0,
  ) = DartValue_Decimal;
  const factory DartValue.str(
    String field0,
  ) = DartValue_Str;
  const factory DartValue.bytea(
    Uint8List field0,
  ) = DartValue_Bytea;
  const factory DartValue.inet(
    IpAddr field0,
  ) = DartValue_Inet;
  const factory DartValue.date(
    NaiveDate field0,
  ) = DartValue_Date;
  const factory DartValue.timestamp(
    DateTime field0,
  ) = DartValue_Timestamp;
  const factory DartValue.time(
    NaiveTime field0,
  ) = DartValue_Time;
  const factory DartValue.interval(
    Interval field0,
  ) = DartValue_Interval;
  const factory DartValue.uuid(
    U128 field0,
  ) = DartValue_Uuid;
  const factory DartValue.map(
    Map<String, Value> field0,
  ) = DartValue_Map;
  const factory DartValue.list(
    List<Value> field0,
  ) = DartValue_List;
  const factory DartValue.point(
    Point field0,
  ) = DartValue_Point;
  const factory DartValue.nullData() = DartValue_NullData;
}
