[package]
name = "gluesql-ex"
authors = [
  "Hoon Wee <mrgravity817@gmail.com>",
  "Taehoon Moon <taehoon.moon@outlook.com>",
]
version.workspace = true
edition.workspace = true
description.workspace = true
license.workspace = true
repository.workspace = true
documentation.workspace = true

[lib]
name = "gluesql"
path = "src/lib.rs"
crate-type = ["cdylib"]


[dependencies]
gluesql-core.workspace = true
memory-storage.workspace = true
rustler = "0.30.0"
serde_json = "1"
tokio = { version = "1", features = [
  "rt",
  "rt-multi-thread",
  "macros",
  "sync",
] }

[dev-dependencies]
test-suite.workspace = true
