[project]
site_name = "GlueSQL"
site_url = "https://gluesql.org/docs/dev/"
site_description = "GlueSQL is quite sticky. It sticks to anything."
docs_dir = "docs"
site_dir = "build"
use_directory_urls = true
nav = [
  "index.md",
  {"Getting Started" = [
    "getting-started/rust.md",
    "getting-started/javascript-web.md",
    "getting-started/nodejs.md",
    "getting-started/cli.md",
  ]},
  {"SQL Syntax" = [
    "sql-syntax/intro.md",
    {"Statements" = [
      {"Querying" = [
        "sql-syntax/statements/querying/where.md",
        "sql-syntax/statements/querying/join.md",
        "sql-syntax/statements/querying/limit.md",
        "sql-syntax/statements/querying/aggregation.md",
        "sql-syntax/statements/querying/schemaless.md",
      ]},
      {"Data definition" = [
        "sql-syntax/statements/data-definition/create-table.md",
        "sql-syntax/statements/data-definition/drop-table.md",
        "sql-syntax/statements/data-definition/create-index.md",
        "sql-syntax/statements/data-definition/drop-index.md",
        "sql-syntax/statements/data-definition/alter-table.md",
      ]},
      {"Data manipulation" = [
        "sql-syntax/statements/data-manipulation/insert.md",
        "sql-syntax/statements/data-manipulation/update.md",
        "sql-syntax/statements/data-manipulation/delete.md",
      ]},
      "sql-syntax/statements/transaction.md",
      {"Metadata" = [
        "sql-syntax/statements/metadata/show-tables.md",
        "sql-syntax/statements/metadata/data-dictionary.md",
      ]},
    ]},
    {"Data types" = [
      "sql-syntax/data-types/boolean.md",
      "sql-syntax/data-types/integers.md",
      "sql-syntax/data-types/float.md",
      "sql-syntax/data-types/text.md",
      "sql-syntax/data-types/decimal.md",
      "sql-syntax/data-types/date.md",
      "sql-syntax/data-types/timestamp.md",
      "sql-syntax/data-types/time.md",
      "sql-syntax/data-types/interval.md",
      "sql-syntax/data-types/list.md",
      "sql-syntax/data-types/map.md",
      "sql-syntax/data-types/point.md",
      "sql-syntax/data-types/bytea.md",
      "sql-syntax/data-types/inet.md",
      "sql-syntax/data-types/uuid.md",
    ]},
    {"Functions" = [
      {"Text" = [
        "sql-syntax/functions/text/ascii.md",
        "sql-syntax/functions/text/chr.md",
        "sql-syntax/functions/text/concat.md",
        "sql-syntax/functions/text/concat-ws.md",
        "sql-syntax/functions/text/find-idx.md",
        "sql-syntax/functions/text/hex.md",
        "sql-syntax/functions/text/initcap.md",
        "sql-syntax/functions/text/left.md",
        "sql-syntax/functions/text/lower.md",
        "sql-syntax/functions/text/lpad.md",
        "sql-syntax/functions/text/ltrim.md",
        "sql-syntax/functions/text/md5.md",
        "sql-syntax/functions/text/position.md",
        "sql-syntax/functions/text/repeat.md",
        "sql-syntax/functions/text/replace.md",
        "sql-syntax/functions/text/reverse.md",
        "sql-syntax/functions/text/right.md",
        "sql-syntax/functions/text/rpad.md",
        "sql-syntax/functions/text/rtrim.md",
        "sql-syntax/functions/text/substr.md",
        "sql-syntax/functions/text/trim.md",
        "sql-syntax/functions/text/upper.md",
      ]},
      {"Math" = [
        "sql-syntax/functions/math/abs.md",
        "sql-syntax/functions/math/acos.md",
        "sql-syntax/functions/math/asin.md",
        "sql-syntax/functions/math/atan.md",
        "sql-syntax/functions/math/ceil.md",
        "sql-syntax/functions/math/cos.md",
        "sql-syntax/functions/math/degrees.md",
        "sql-syntax/functions/math/div.md",
        "sql-syntax/functions/math/exp.md",
        "sql-syntax/functions/math/floor.md",
        "sql-syntax/functions/math/gcd.md",
        "sql-syntax/functions/math/lcm.md",
        "sql-syntax/functions/math/ln.md",
        "sql-syntax/functions/math/log.md",
        "sql-syntax/functions/math/log10.md",
        "sql-syntax/functions/math/log2.md",
        "sql-syntax/functions/math/mod.md",
        "sql-syntax/functions/math/pi.md",
        "sql-syntax/functions/math/power.md",
        "sql-syntax/functions/math/radians.md",
        "sql-syntax/functions/math/rand.md",
        "sql-syntax/functions/math/round.md",
        "sql-syntax/functions/math/sign.md",
        "sql-syntax/functions/math/sin.md",
        "sql-syntax/functions/math/sqrt.md",
        "sql-syntax/functions/math/tan.md",
        "sql-syntax/functions/math/trunc.md",
      ]},
      {"Date & Time" = [
        "sql-syntax/functions/datetime/add-month.md",
        "sql-syntax/functions/datetime/extract.md",
        "sql-syntax/functions/datetime/format.md",
        "sql-syntax/functions/datetime/last-day.md",
        "sql-syntax/functions/datetime/now.md",
        "sql-syntax/functions/datetime/to-date.md",
        "sql-syntax/functions/datetime/to-time.md",
        "sql-syntax/functions/datetime/to-timestamp.md",
      ]},
      {"List & Map" = [
        "sql-syntax/functions/list-map/append.md",
        "sql-syntax/functions/list-map/concat.md",
        "sql-syntax/functions/list-map/dedup.md",
        "sql-syntax/functions/list-map/entries.md",
        "sql-syntax/functions/list-map/is-empty.md",
        "sql-syntax/functions/list-map/keys.md",
        "sql-syntax/functions/list-map/length.md",
        "sql-syntax/functions/list-map/prepend.md",
        "sql-syntax/functions/list-map/skip.md",
        "sql-syntax/functions/list-map/slice.md",
        "sql-syntax/functions/list-map/sort.md",
        "sql-syntax/functions/list-map/splice.md",
        "sql-syntax/functions/list-map/take.md",
        "sql-syntax/functions/list-map/values.md",
      ]},
      {"Geometry" = [
        "sql-syntax/functions/geometry/calc-distance.md",
        "sql-syntax/functions/geometry/get-x.md",
        "sql-syntax/functions/geometry/get-y.md",
        "sql-syntax/functions/geometry/point.md",
      ]},
      {"Others" = [
        "sql-syntax/functions/others/cast.md",
        "sql-syntax/functions/others/coalesce.md",
        "sql-syntax/functions/others/generate-uuid.md",
        "sql-syntax/functions/others/greatest.md",
        "sql-syntax/functions/others/ifnull.md",
        "sql-syntax/functions/others/nullif.md",
      ]},
    ]},
  ]},
  {"Query Builder" = [
    "query-builder/intro.md",
    {"Statements" = [
      {"Querying" = [
        "query-builder/statements/querying/fetching-data-from-storage.md",
        "query-builder/statements/querying/using-preloaded-data.md",
        "query-builder/statements/querying/creating-derived-subqueries.md",
        "query-builder/statements/querying/data-aggregation.md",
        "query-builder/statements/querying/data-injection.md",
        "query-builder/statements/querying/data-joining.md",
        "query-builder/statements/querying/data-selection-and-projection.md",
        "query-builder/statements/querying/data-sorting-and-limiting.md",
      ]},
      {"Data Manipulation" = [
        "query-builder/statements/data-manipulation/inserting-data.md",
        "query-builder/statements/data-manipulation/updating-data.md",
        "query-builder/statements/data-manipulation/deleting-data.md",
      ]},
    ]},
    {"Expressions" = [
      "query-builder/expressions/conditional.md",
      "query-builder/expressions/nested.md",
      "query-builder/expressions/operator-based.md",
      "query-builder/expressions/pattern-matching.md",
      "query-builder/expressions/value-checking.md",
    ]},
    {"Functions" = [
      {"Text" = [
        "query-builder/functions/text/case-conversion.md",
        "query-builder/functions/text/character-conversion.md",
        "query-builder/functions/text/padding.md",
        "query-builder/functions/text/position-and-indexing.md",
        "query-builder/functions/text/text-manipulation.md",
        "query-builder/functions/text/trimming.md",
      ]},
      {"Math" = [
        "query-builder/functions/math/basic-arithmetic.md",
        "query-builder/functions/math/conversion.md",
        "query-builder/functions/math/logarithmic-and-exponential.md",
        "query-builder/functions/math/rounding.md",
        "query-builder/functions/math/special-mathematical.md",
        "query-builder/functions/math/trigonometric.md",
      ]},
      {"Date & Time" = [
        "query-builder/functions/date-&-time/conversion.md",
        "query-builder/functions/date-&-time/current-date-and-time.md",
        "query-builder/functions/date-&-time/date-and-time-extraction.md",
        "query-builder/functions/date-&-time/formatting.md",
      ]},
      {"List & Map" = [
        "query-builder/functions/list-&-map/list-and-map-concatenation.md",
        "query-builder/functions/list-&-map/list-manipulation.md",
      ]},
      {"Geometry" = [
        "query-builder/functions/geometry/coordinate-extraction.md",
        "query-builder/functions/geometry/distance-calculation.md",
        "query-builder/functions/geometry/point-creation.md",
      ]},
      {"Others" = [
        "query-builder/functions/others/null-handling.md",
        "query-builder/functions/others/type-conversion.md",
        "query-builder/functions/others/unique-identifier.md",
      ]},
    ]},
  ]},
  {"Storages" = [
    "storages/intro.md",
    {"Supported Storages" = [
      "storages/supported-storages/composite-storage.md",
      "storages/supported-storages/csv-storage.md",
      "storages/supported-storages/file-storage.md",
      "storages/supported-storages/git-storage.md",
      "storages/supported-storages/json-storage.md",
      "storages/supported-storages/memory-storage.md",
      "storages/supported-storages/mongo-storage.md",
      "storages/supported-storages/parquet-storage.md",
      "storages/supported-storages/redb-storage.md",
      "storages/supported-storages/redis-storage.md",
      "storages/supported-storages/shared-memory-storage.md",
      "storages/supported-storages/sled-storage.md",
    ]},
    {"Developing Custom Storages" = [
      "storages/developing-custom-storages/intro.md",
      {"Understanding Store traits" = [
        "storages/developing-custom-storages/store-traits/store.md",
        "storages/developing-custom-storages/store-traits/store-mut.md",
        "storages/developing-custom-storages/store-traits/alter-table.md",
        "storages/developing-custom-storages/store-traits/transaction.md",
        "storages/developing-custom-storages/store-traits/custom-function.md",
        "storages/developing-custom-storages/store-traits/custom-function-mut.md",
        "storages/developing-custom-storages/store-traits/index-trait.md",
        "storages/developing-custom-storages/store-traits/index-mut.md",
        "storages/developing-custom-storages/store-traits/metadata.md",
      ]},
      "storages/developing-custom-storages/using-test-suite.md",
    ]},
  ]},
  {"Archive" = [
    {"Articles" = [
      "articles/index.md",
      "articles/breaking-the-boundary-between-sql-and-nosql.md",
      "articles/revolutionizing-databases-by-unifying-query-interfaces.md",
      "articles/test-driven-documentation.md",
    ]},
    {"Releases" = [
      "releases/index.md",
      "releases/release-v0.14.md",
      "releases/release-v0.15.md",
    ]},
  ]},
]

[project.extra]
homepage = "https://gluesql.org/docs"

[project.theme]
custom_dir = "overrides"
favicon = "assets/favicon.ico"
features = [
  "navigation.path",
]
