DROP TABLE category;
CREATE TABLE category (
  categoryid integer,
  categoryname text,
  categorydescription text
);

INSERT INTO category (categoryid, categoryname, categorydescription) VALUES
(5, 'Barnkalasmat', ''),
(6, 'Bröd', ''),
(7, 'Dessert', ''),
(8, 'Dryck', ''),
(9, 'Fisk', 'Alla sorters fisk. Både havs och insjö.'),
(10, 'Franskt', ''),
(11, 'Förrätt', ''),
(12, 'Huvudrätt', ''),
(13, 'Indiskt', ''),
(14, 'Italienskt', ''),
(15, 'Kaka', ''),
(16, 'Korvrätter', ''),
(17, 'Kyckling', ''),
(18, 'Lamm', ''),
(19, 'Lax', ''),
(20, 'Mackor', ''),
(21, 'Mexikanskt', ''),
(22, 'Paj', ''),
(23, 'Pastasås', ''),
(24, 'Potatisrätter', ''),
(25, 'Påsk', 'Passar till påsken'),
(27, 'Soppa', ''),
(28, 'Spanskt', ''),
(29, 'Stek', 'Stekar på allt slags kött i ugn eller gryta.'),
(30, 'Såser', ''),
(31, 'Thai', ''),
(32, 'Skaldjur', ''),
(33, 'Pasta', ''),
(35, 'Sillrätt', ''),
(36, 'Nöt', ''),
(38, 'Wok', ''),
(39, 'Ugn', ''),
(40, 'Lunch', ''),
(41, 'Puré', ''),
(42, 'Buffé', ''),
(43, 'Gryta', ''),
(44, 'Yoghurt', ''),
(45, 'Grill', ''),
(46, 'Omelett', ''),
(48, 'Vilt', ''),
(49, 'Kalv', ''),
(53, 'Fläskkött', ''),
(54, 'Vegetarisk', ''),
(55, 'Pastej', ''),
(56, 'Gratäng', ''),
(57, 'Finskt', ''),
(58, 'Kassler', '');