name: Assign a PR to the person who created it

on:
  pull_request_target:
    branches: [ "main" ]

jobs:
  assign-pr:
    runs-on: ubuntu-latest

    steps:
      - name: Add assignees to an PR
        run: |
          HTTP_RESP_CODE=$(curl -o /dev/null  -w "%{http_code}" -X POST -H "Accept: application/vnd.github+json" -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.number }}/assignees -d '{"assignees":["${{ github.event.sender.login }}"]}')
          if [[ $HTTP_RESP_CODE != 201 ]]; then
            echo "Add assignees to an PR failed ($HTTP_RESP_CODE)"
            exit 1
          fi