name: auto-author-assign

on:
  pull_request_target:
    types: [opened, ready_for_review]

permissions:
  pull-requests: write

jobs:
  assign-author:
    runs-on: ubuntu-latest
    steps:
      - uses: kentaro-m/auto-assign-action@v2.0.0
        with:
          configuration-path: '.github/auto-author-assign-config.yml'
