name: Rust

on:
  push:
    branches: [main, release-*]
    paths-ignore:
      - "docs/**"
  pull_request:
    paths-ignore:
      - "docs/**"

env:
  CARGO_TERM_COLOR: always

jobs:
  clippy_workspace:
    name: Clippy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: Swatinem/rust-cache@v2
      - run: cargo clippy --all-targets -- -D warnings

  rust_fmt:
    name: Rustfmt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: Swatinem/rust-cache@v2
      - run: |
          cargo fmt -- --check

  rust_build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: Swatinem/rust-cache@v2
      - run: cargo build --all-features --verbose

  run_tests:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: Swatinem/rust-cache@v2
      - run: |
          set -euxo pipefail
          cargo test -p gluesql-macros --verbose
          cargo test -p gluesql-core --verbose
          cargo test -p gluesql-utils --verbose
          cargo test -p gluesql-cli --verbose
          cargo test -p gluesql --lib --bins --tests --examples --verbose --no-default-features --features "gluesql_memory_storage gluesql_sled_storage"

  run_storage_tests:
    name: Run storage tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: Swatinem/rust-cache@v2
      - run: |
          set -euxo pipefail
          cargo test -p gluesql_memory_storage --verbose
          cargo test -p gluesql-shared-memory-storage --verbose
          cargo test -p gluesql-composite-storage --verbose
          cargo test -p gluesql-json-storage --verbose
          cargo test -p gluesql-csv-storage --verbose
          cargo test -p gluesql-parquet-storage --verbose
          cargo test -p gluesql-file-storage --verbose
          cargo test -p gluesql-redb-storage --verbose
          cargo test -p gluesql_sled_storage --verbose -- --skip sled_transaction_timeout
          cargo test -p gluesql_sled_storage sled_transaction_timeout --verbose -- --test-threads=1
          cargo test -p gluesql_sled_storage --benches

  run_mongostorage_tests:
    name: Run MongoStorage tests
    runs-on: ubuntu-latest
    services:
      mongo:
        image: mongo:latest
        ports:
          - 27017:27017
        options: >-
          --health-cmd "mongosh --quiet --eval \"db.adminCommand('ping').ok\""
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - uses: actions/checkout@v6
      - uses: Swatinem/rust-cache@v2
      - run: |
          cargo test -p gluesql-mongo-storage --verbose --features test-mongo

  run_redisstorage_tests:
    name: Run RedisStorage tests
    runs-on: ubuntu-latest
    services:
      redis:
        image: redis:6
        ports:
          - 6379:6379
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - uses: actions/checkout@v6
      - uses: Swatinem/rust-cache@v2
      - run: |
          cargo test -p gluesql-redis-storage --verbose --features test-redis

  run_gitstorage_tests:
    name: Run GitStorage tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: Swatinem/rust-cache@v2

      - name: Prepare
        run: |
          git config --global user.email "gitstorage.bot@gluesql.org"
          git config --global user.name "GitStorage Bot"

      - name: Test
        env:
          GIT_REMOTE: https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
        run: |
          GIT_REMOTE=$GIT_REMOTE cargo test -p gluesql-git-storage --verbose --features test-git-remote

  run_examples:
    name: Run examples
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: Swatinem/rust-cache@v2
      - run: |
          cargo run --package gluesql --example hello_world
          cargo run --package gluesql --example api_usage
          cargo run --package gluesql --example memory_storage_usage
          cargo run --package gluesql --example sled_multi_threaded
          cargo run --package gluesql --example using_config
          cargo run --package gluesql --example hello_ast_builder
          cargo run --package gluesql --example parameter_binding
